services:
  spring-app:
    image: lexilearn-api-gateway-spring-boot
    container_name: lexilearn-api-gateway-spring-boot-container
    network_mode: host

    ports:
      - '5000:5000'
    environment:
      PORT: ${PORT}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      USER_SERVICE_API_KEY: ${USER_SERVICE_API_KEY}
      JAVA_ENV: ${JAVA_ENV}
      DELAY_TIME: ${DELAY_TIME}
      CLIENT_SERVER: ${CLIENT_SERVER}
      IMAGE_SERVER: ${IMAGE_SERVER}
      IMAGE_SERVER_API_KEY: ${IMAGE_SERVER_API_KEY}
      ELASTICSEARCH_SERVER: ${ELASTICSEARCH_SERVER}
      GENERATOR_SERVER: ${GENERATOR_SERVER}
      GENERATOR_SERVER_API_KEY: ${GENERATOR_SERVER_API_KEY}
      GENERATOR_SERVER_SUBSCRIPTION_KEY: ${GENERATOR_SERVER_SUBSCRIPTION_KEY}
