# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go deploy

on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Transfer Config File
      run: |
          echo "${{ secrets.CONFIG_YML_BASE64 }}" | base64 --decode > config.yml
    - name: Build
      run: go build -o main ./src/main.go

    - name: Run
      run: ./main
